### PR TITLE
Allow ResultSet slicing

### PR DESCRIPTION
**Pull request by hoetmaaiers**

### CODE REVIEW

**Comment by bouweandela** [comment]
Thanks for taking the time to contribute! Could you please remove the [whitespace from line 48](https://github.com/ESGF/esgf-pyclient/actions/runs/9367408823/job/26943116844?pr=104)?

A unit test would be much appreciated if you have the time.

**Comment by hoetmaaiers** [comment]
The whitespace is removed, the unit test won't be for anytime soon...

**Comment by bouweandela** [comment]
Thanks! The test failure appears to be unrelated to this pull request.

**Comment by valeriupredoi** [comment]
many thanks folks, I'm "fixing" the test failure in #105

**Review by valeriupredoi — APPROVED** [review]

**Pull request merged**
