### PR TITLE
Changes for testing with Python 3

### PR DESCRIPTION
**Pull request by philipkershaw**
Testing with Python 3.  Added fix for test_context (not the expected number of search hits), also added six in package dependencies and
incremented version to 0.2.0

### CODE REVIEW

**Comment by lewismc** [comment]
```
$ python --version
Python 3.6.1 :: Continuum Analytics, Inc.
```

Hi @philipkershaw @laliberte @agstephens I tested this locally and I get the following 
```
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.6.1, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /usr/local/esgf-pyclient, inifile:
collected 125 items

test_ats.py xx.                                                                                                                                                                                      [  2%]
test_connection.py .......                                                                                                                                                                           [  8%]
test_context.py ...............                                                                                                                                                                      [ 20%]
test_logon.py ssssssss                                                                                                                                                                               [ 26%]
test_multidict.py ......................................................................                                                                                                             [ 82%]
test_opendap.py sss                                                                                                                                                                                  [ 84%]
test_results.py ........x...                                                                                                                                                                         [ 94%]
test_shard_regex.py .                                                                                                                                                                                [ 95%]
test_temporal_search.py ..                                                                                                                                                                           [ 96%]
test_util.py ...                                                                                                                                                                                     [ 99%]
test_wget.py .                                                                                                                                                                                       [100%]

============================================================================================= warnings summary =============================================================================================
pyesgf/test/test_connection.py::TestConnection::test_url_fixing
  /Users/lmcgibbn/miniconda3/lib/python3.6/site-packages/esgf_pyclient-0.2.0-py3.6.egg/pyesgf/search/connection.py:140: UserWarning: Old-style SearchContext URL specified.  In future please specify the URL excluding the "/search" endpoint.
    warnings.warn('Old-style SearchContext URL specified.  '

-- Docs: http://doc.pytest.org/en/latest/warnings.html
===================================================================== 111 passed, 11 skipped, 3 xfailed, 1 warnings in 152.18 seconds
```

**Comment by laliberte** [comment]
As far as I remember, the code was essentially ported to python 3 except for the MyProxyClient (the skipped test_logon, see #12).

**Comment by philipkershaw** [comment]
I ported MyProxyClient to Python 3.  It's in PyPI.  However, when I tested with esgf-pyclient I saw some strange behaviour with the pyOpenSSL dependency.

**Comment by lewismc** [comment]
@philipkershaw the functionality to read the config variables could be improved by first checking for a local file pyesgf.cfg (or something similar) rather than limiting checks to the OS. This would also mean we could essentially set up dummy user, pass, etc. for CI tests only...
wdyt?

**Pull request merged**
