### PR TITLE
Added MANIFEST.in

### PR DESCRIPTION
**Pull request by agoodm**
Hi @agstephens,

Our team uses esgf-pyclient for downloading climate data from the ESGF. Currently we are trying to upload the package to the [conda-forge](http://conda-forge.github.io), but the maintainers would like to ensure that the LICENSE file is included with each `sdist` (see [here](https://github.com/conda-forge/staged-recipes/pull/1610)), which is the reason I have made this PR. Would you be able to merge this and update the package on PyPI accordingly?

Thanks.

### CODE REVIEW

**Comment by agoodm** [comment]
Can you merge this @agstephens ? I have already uploaded the packaged to conda-forge (so you can just do `conda install -c conda-forge esgf-pyclient` to install the package), but would like to get this resolved ASAP. Thanks.

**Comment by agstephens** [comment]
Hi @agoodm, very sorry for losing track of this one. Thanks for uploading to conda-forge. Ag

**Comment by agoodm** [comment]
@agstephens Thank you. I'll keep in touch since there are other things that we would like to see updated with esgf-pyclient / myproxyclient.

**Comment by agstephens** [comment]
Hi @agoodm, sounds good. I'm juggling lots of things at present so please bug me if I'm slow in responding. Thanks, Ag

**Comment by philipkershaw** [comment]
@agoodm, do let me know what you're looking for with MyProxyClient

**Comment by agoodm** [comment]
@philipkershaw Most likely back then I was referring to Python 3 support, but it looks like you have long since taken care of that :)

**Pull request merged**
